name: Docker Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Trigger only when `index.html` is modified

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t vishalgujare27/html-repo:latest .

      - name: Push Docker image
        run: |
          docker push vishalgujare27/html-repo:latest
          
      - name: SSH into server and deploy container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop html-container || true
            docker rm html-container || true
            docker run -d --name html-container -p 80:80 vishalgujare27/html-repo:latest
